name: test_drive
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  speech_to_text: ^6.0.0
  get_it: ^7.2.0
  flutter_riverpod: ^2.5.1
  audioplayers: ^6.0.0
  firebase_core: ^2.27.2
  firebase_database: ^10.4.11
  flutter_tts: ^3.6.3
  flutter_sound: ^9.2.13

  english_words: ^4.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/data/hardcoded.txt
    - assets/data/claud.json
    - assets/data/claudopus.json
    - assets/audio/cash.mp3